<a href="https://colab.research.google.com/github/robertosgpontes/tec_prog_1/blob/main/ExerciciosNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

In [10]:
import numpy as np

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [13]:
my_array = np.random.randint(0, 1000, 100)

print(my_array.min())
print(my_array.max())
my_array

24
986


array([ 24, 457, 904, 356, 639, 127,  38, 760, 417, 136,  77, 139, 274,
       934,  99, 844, 359, 910, 210, 136, 840,  48,  25, 907, 181, 704,
       259, 899,  49, 145, 264, 645, 404, 489, 141, 143, 709, 659,  43,
       983, 298, 616, 208,  57, 933, 640, 611, 967, 986, 674, 608, 250,
       492, 390, 426, 419, 872,  67, 785, 678, 748, 681, 348, 277, 450,
       300, 220, 186, 570, 521, 513, 635, 401, 186, 175, 167, 284, 211,
       120, 973, 789, 116, 528, 937, 709, 871, 201, 356, 456,  49, 595,
       724, 128, 115, 114, 947, 422, 295, 231, 267])

## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [20]:
#%%timeit 

def modulo_vetor(arr):
  mod = np.sqrt((arr**2).sum())
  return mod

my_vector = modulo_vetor(np.array([22, 70]))
my_vector

73.37574531137656

## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

```python

# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

>>> 1.6666666666666665

```

In [29]:
# Solução
def calculate_eqm(y_prediction, y_i):
    return np.mean((y_prediction - y_i)**2)

y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

1.6666666666666667

## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [30]:
my_array = np.ones((3, 3))
my_array[1][1] = 0
my_array

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [31]:
my_array = np.array(([1,2,3], [4,5,6]))
print(my_array)
my_array_aux = np.zeros((4, 5))
my_array_aux[1][1:4] = my_array[0]
my_array_aux[2][1:4] = my_array[1]
my_array_aux


[[1 2 3]
 [4 5 6]]


array([[0., 0., 0., 0., 0.],
       [0., 1., 2., 3., 0.],
       [0., 4., 5., 6., 0.],
       [0., 0., 0., 0., 0.]])

## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

```python

# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões
>>> (64, 512)

# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape
>>> (64, 512)

# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()
>>> -53.08727366483029

# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X
>>> array([[ 0.29305925,  0.89663038, -0.61032202, ..., -0.88086364,
        -0.8818789 ,  0.51260497],
       [-0.01274415,  1.05439522,  0.47958092, ..., -2.15387924,
         0.70721168,  0.97029889],
       [ 1.09478371, -0.16120847,  1.58400361, ...,  0.20981813,
         2.17373837,  0.94032162],
       ...,
       [-0.45294842, -2.28939505,  1.10111998, ...,  1.63581703,
        -0.39394924, -1.13400723],
       [-0.22669886,  0.25413429, -1.17870637, ..., -0.09509442,
         0.90733806,  0.37999411],
       [ 0.15476933, -0.03654717, -1.09982762, ...,  0.67600047,
        -0.84533328, -0.56433144]])

# Matriz após o processamento descrito no enunciado
X_processado

>>> array([[ 0.36713022,  0.85772513, -0.54902169, ..., -0.85626087,
        -0.97611435,  0.51718998],
       [ 0.06132682,  1.01548997,  0.54088126, ..., -2.12927647,
         0.61297623,  0.97488389],
       [ 1.16885469, -0.20011372,  1.64530394, ...,  0.23442091,
         2.07950292,  0.94490663],
       ...,
       [-0.37887744, -2.3283003 ,  1.16242031, ...,  1.6604198 ,
        -0.4881847 , -1.12942223],
       [-0.15262788,  0.21522904, -1.11740604, ..., -0.07049164,
         0.81310261,  0.38457911],
       [ 0.22884031, -0.07545242, -1.03852729, ...,  0.70060324,
        -0.93956874, -0.55974643]])

```

In [32]:
# Solução
def process_array(x):
    media = np.mean(x, axis=0)
    x_ok = x - media
    return x_ok


X_processado = process_array(X)
print(X_processado)

[[ 0.70829043 -0.32938067 -0.31996149 ... -0.59157681 -0.48624849
  -0.13712561]
 [-1.13499773 -0.18350432  0.58229204 ...  0.45143754  1.74883966
   0.47449781]
 [-1.29129006 -0.396667    0.01487429 ...  0.0206838   0.13761839
   0.97439054]
 ...
 [-0.35563314 -1.64485476 -0.17619586 ... -0.11595144 -0.69907839
   0.20637473]
 [ 1.49936281 -0.49352008  1.92296421 ... -0.47490479  0.06812531
   1.49301081]
 [-0.07428146 -0.7695767   0.48703253 ... -0.82541946 -0.97028293
  -0.60799439]]


## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo do Limite Inferior (LI = Q1 - 1.5*IQR  ), ou acima do Limite Superior (LS = Q3 + 1.5*IQR).

![image.png](https://s3-sa-east-1.amazonaws.com/lcpi/0d8a7b04-b982-4e6b-9fc7-fbb062247d8d.png)


<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

```python
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

>>> array([[-2.02108952,  0.57945921, -2.23074965, ..., -0.60349514,
         0.92180452, -0.15625722],
       [ 0.24904397,  0.03493447,  0.3515052 , ..., -0.46950081,
         0.20361331,  0.02715956],
       [ 0.55902525, -0.48435434,  0.90413414, ..., -0.54425743,
        -0.80769134, -0.07912549],
       ...,
       [-1.04069388, -0.24245725, -2.00308877, ...,  0.4084777 ,
        -1.81516131,  0.39063118],
       [-1.39275097,  0.3989636 ,  0.2926223 , ...,  1.2620666 ,
         0.72262949,  1.50737559],
       [ 0.15922011, -0.79810788, -1.60939896, ..., -0.08214499,
        -0.13167475,  0.15990558]])


# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

is_outlier
>>> array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

outliers_count
>>> 44

outliers
>>> array([-2.67240384,  3.00270904,  3.62317101,  3.18867865,  2.55581522,
       -2.82091429,  2.8757892 ,  2.70666036,  3.19514999, -3.40550318,
       -3.39825827,  2.6727295 ,  2.54498296, -2.69447104,  3.19521603,
        2.66372172, -2.77444948,  2.77421152,  2.69992869, -2.84831109,
       -2.83695779, -2.45908227,  3.07802106,  2.89314015, -2.68574682,
       -2.85019494,  2.43399574,  2.44291266, -2.92595937, -2.95911074,
       -3.03966003,  2.77543068, -2.67368414, -2.79965402, -3.0501958 ,
       -2.5437387 ,  3.08550649, -3.17666255, -3.05795476, -3.09826467,
        3.1399469 ,  3.18141942,  2.90564257, -2.89505054])

 ``` 

In [35]:
# Solução
X = np.random.randn(300,15)
def locate_outliers(X):
    mean = np.mean(X, axis=0)
    std = np.std(X, axis=0)
    is_outlier = np.abs(X - mean) > 3 * std
    outliers_count = np.sum(is_outlier)
    outliers = X[is_outlier]
    return is_outlier, outliers_count, outliers

is_outlier, outliers_count, outliers = locate_outliers(X)
print(is_outlier)
print(outliers_count)
print(outliers)

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
11
[ 3.46355904 -3.42917259  3.17221173  2.8312043   3.88187393 -3.2618199
 -3.30829068  3.22034514  4.0887778   3.05246525 -3.4670947 ]


## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [37]:
my_vector = np.arange(1, 22, 2)
my_vector


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

## Questão 9

Crie um array de 10 com valores aleatórios

In [38]:
my_array_10 = np.random.randint(0, 100, 10)
my_array_10

array([53, 25, 76, 65, 36, 55, 47, 87, 10, 72])

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [39]:
def normalize(vetor):
    std = vetor.std()
    media = vetor.mean()
    normalizado = (vetor - media) / std
    return normalizado

my_array_norm = normalize(my_array_10)
my_array_norm

array([ 0.01762542, -1.21615408,  1.03108716,  0.54638807, -0.73145499,
        0.10575253, -0.2467559 ,  1.51578625, -1.87710739,  0.85483294])

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [42]:
notas = np.random.randint(0, 100, 100)/10
print(notas)
def estatistic(vetor):
    media = vetor.mean()
    desvio = vetor.std()
    maior7 = np.unique(np.where(vetor >= 7), return_counts=True)
    reprovados = np.unique(np.where(vetor < 5), return_counts=True)
    maior = vetor.max()
    menor = vetor.min()
    my_list = [media, desvio, np.sum(maior7[1]), np.sum(reprovados[1]), menor, maior]
    return np.array(my_list)

my_estatistic = estatistic(notas)
my_estatistic

[3.7 5.5 2.6 6.4 6.4 0.  0.7 1.8 8.7 3.9 1.1 7.4 7.9 0.1 0.4 4.3 1.1 4.1
 3.  1.6 8.5 9.7 1.3 7.1 9.2 6.7 4.4 5.2 4.9 0.6 1.3 4.6 3.6 9.9 4.7 2.6
 0.8 3.  5.2 2.5 5.1 1.7 6.8 5.5 5.5 7.8 7.4 4.  5.9 0.1 2.5 3.1 5.1 2.4
 4.7 7.7 7.5 5.4 9.9 9.  4.5 0.8 9.7 8.8 2.9 8.4 7.2 0.2 5.2 6.3 5.6 4.1
 5.7 9.  5.  1.5 1.7 7.5 6.4 3.  4.9 6.1 1.3 8.9 0.4 1.7 3.4 5.  6.6 7.
 5.  5.2 7.9 0.4 8.  2.1 9.  1.1 3.2 2.1]


array([ 4.664     ,  2.79390479, 25.        , 51.        ,  0.        ,
        9.9       ])